name: Code Quality Checks
description: Run code quality checks using pre-commit
inputs:
  python_version:
    required: true
    type: string
  pip_deps:
    required: true
    type: string
  safe_directory:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}
  - name: Setup
    shell: bash
    run: |
      set -ex
      pip install uv
      uv pip install --upgrade --system pip wheel
      uv pip install --system .${{ inputs.pip_deps }}
  - name: Run checks
    shell: bash
    run: |
      git config --global --add safe.directory /__w/${{ inputs.safe_directory }}/${{ inputs.safe_directory }}
      pre-commit run --all-files
