name: Code Quality Checks
description: Run code quality checks using pre-commit
inputs:
  python_version:
    required: true
    type: string
  pip_deps:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}
  - name: Activate virtualenv
    shell: bash
    run: |
      python -m venv .venv
      . .venv/bin/activate
      echo PATH=$PATH >> $GITHUB_ENV
  - name: Setup
    shell: bash
    run: |
      set -ex
      pip install --system uv
      uv pip install --upgrade --system pip wheel
      uv pip install --upgrade --system .${{ inputs.pip_deps }}
  - name: Run checks
    shell: bash
    run: |
      pre-commit run --all-files
