name: Code Quality Checks
description: Run code quality checks using pre-commit
inputs:
  python_version:
    required: true
    type: string
  pip_deps:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}
  - name: Setup
    shell: bash
    run: |
      set -ex
      python -m pip install --upgrade 'pip<23' wheel
      python -m pip install --upgrade .${{ inputs.pip_deps }}
  - name: Run checks
    shell: bash
    run: |
      pre-commit run --all-files
