name: Smoketest
inputs:
  python_version:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}
  - name: Setup
    shell: bash
    run: |
      set -ex
      python -m venv ~/.local
      source ~/.local/bin/activate
      pip install uv
      uv pip install --upgrade --system pip wheel
      uv pip install --upgrade --system .
      uv pip install --system pytest==7.2.1 pytest_codeblocks==0.16.1
  - name: Run checks
    shell: bash
    run: |
      source ~/.local/bin/activate
      pytest tests/test_smoketest.py
