name: Smoketest
inputs:
  python_version:
    required: true
    type: string
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: ${{ inputs.python_version }}
  - name: Activate virtualenv
    shell: bash
    run: |
      python -m venv .venv
      . .venv/bin/activate
      echo PATH=$PATH >> $GITHUB_ENV
  - name: Setup
    shell: bash
    run: |
      set -ex
      pip install uv
      uv pip install --upgrade pip wheel
      uv pip install --upgrade .
      uv pip install pytest==7.2.1 pytest_codeblocks==0.16.1
  - name: Run checks
    shell: bash
    run: |
      pytest tests/test_smoketest.py
