name: Pytest GPU
inputs:
  container:
    required: true
    type: string
  gha-timeout:
    required: false
    type: number
    default: 60
  git-repo:
    required: true
    type: string
  name:
    required: true
    type: string
  pip-deps:
    required: true
    type: string
  pytest-command:
    required: true
    type: string
  pytest-markers:
    required: true
    type: string
  python-version:
    required: false
    type: string
    default: 3.9
  mcloud-timeout:
    required: false
    type: number
    default: 2700
  composer-package-name:
    required: false
    type: string
  git-ssh-clone:
    required: false
    type: boolean
    default: false
  gpu-num:
    required: true
    type: number
  mcloud-api-key:
    required: true
  slack-notifications-bot-token:
    required: false
  code-eval-device:
    required: false
  code-eval-url:
    required: false
  code-eval-apikey:
    required: false
runs:
  using: composite
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        repository: "mosaicml/ci-testing"
        ref: "kevin/remove-pin-version"
    - name: Set Environment Variables
      shell: bash
      run: |
        export MOSAICML_API_KEY='${{ inputs.mcloud-api-key }}'
        export SLACK_NOTIFICATIONS_BOT_TOKEN='${{ inputs.slack-notifications-bot-token }}'
        export CODE_EVAL_DEVICE='${{ inputs.code-eval-device }}'
        export CODE_EVAL_URL='${{ inputs.code-eval-url }}'
        export CODE_EVAL_APIKEY='${{ inputs.code-eval-apikey }}'
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Setup MCLI
      shell: bash
      run: |
        set -ex
        python -m pip install mosaicml-cli
        mcli version
    - name: Submit Run
      id: tests
      shell: bash
      run: |
        set -ex

        PR_NUMBER="$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")"
        REF_ARGS=""

        # Use the PR number if it exists, commit SHA for protected branches and the branch name otherwise
        if [ -z "$PR_NUMBER" ] || [ "$PR_NUMBER" = "null" ]; then
          if [[ "$GITHUB_REF" =~ "refs/heads/dev" || "$GITHUB_REF" =~ "refs/heads/main" || \
            "$GITHUB_REF" =~ "refs/heads/release" ]]; then
            REF_ARGS="--git_commit $GITHUB_SHA"
          else
            REF_ARGS="--git_branch $GITHUB_REF_NAME"
          fi
        else
          REF_ARGS="--pr_number $PR_NUMBER"
        fi

        python .github/mcli/mcli_pytest.py \
          --image '${{ inputs.container }}' \
          --git_repo '${{ inputs.git-repo }}' \
          --pip_deps '${{ inputs.pip-deps }}' \
          --pip_package_name '${{ inputs.composer-package-name }}' \
          --pytest_markers '${{ inputs.pytest-markers }}' \
          --pytest_command '${{ inputs.pytest-command }}' \
          --timeout ${{ inputs.mcloud-timeout }} \
          --gpu_num ${{ inputs.gpu-num }} \
          --git_ssh_clone ${{ inputs.git-ssh-clone }} \
          ${REF_ARGS}
